name: 'Latest Newsletter'
description: 'Fetches the latest newsletter edition from a Substack RSS feed'
inputs:
  rss_url:
    description: 'URL of the Substack RSS feed'
    required: true
outputs:
  latest_newsletter:
    description: 'The latest newsletter content'
runs:
  using: 'node12'
  main: 'newsletter-workflow.js'
