name: Update README with Newsletter

permissions:
  contents: write

on:
  schedule:
    - cron: '0 * * * *' # Runs every hour
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: latest newsletter
        id: fetch-newsletter
        uses: advaith-unnikrishnan/newsletter-workflow@master
        with:
          rss_url: 'https://advaithu.substack.com/feed'

      - name: Update README
        run: |
          echo "Updating README with the latest newsletter edition"
          python update_readme.py "${{ steps.fetch-newsletter.outputs.latest_newsletter }}"
      
      - name: Commit changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add README.md
          git commit -m "Update README with latest newsletter"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
