name: Update README with Newsletter

on:
  schedule:
    - cron: '0 * * * *' # Runs every hour
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: latest newsletter
        id: fetch-newsletter
        uses: <your-github-username>/<your-action-repo>@main
        with:
          rss_url: 'https://<your-substack>.substack.com/feed'

      - name: Update README
        run: |
          echo "Updating README with the latest newsletter edition"
          python update_readme.py "${{ steps.fetch-newsletter.outputs.latest_newsletter }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
