name: Update README with Substack Newsletter

on:
  schedule:
    - cron: '0 0 * * *' # Runs every day at midnight
  workflow_dispatch: # Allow manual workflow runs

jobs:
  update-readme:
    runs-on: ubuntu-latest
    using: 'node20'

    steps:
    # Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v3

    # Install Node.js
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 20.x

    # Install dependencies
    - name: Install dependencies
      run: npm ci

    # Update README
    - name: Update README with Substack Newsletter
      run: node update-readme.js

    # Commit and push changes
    - name: Commit and push changes
      run: |
        git config --global user.name 'GitHub Actions'
        git config --global user.email 'actions@github.com'
        git add README.md
        git commit -m "Update README with latest Substack newsletter editions"
        git push